# Generated by Django 3.2.4 on 2021-09-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Mezmun')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Yazilma Tarixi')),
            ],
        ),
        migrations.CreateModel(
            name='Filemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('description', models.TextField(null=True, verbose_name='Açıqlama')),
                ('file', models.FileField(upload_to='files', verbose_name='Fayl')),
                ('created_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('see_comments', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shared_files', to='file.filemodel')),
            ],
        ),
    ]
