# Generated by Django 3.2.4 on 2021-09-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_sharemodel_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemodel',
            name='sender',
            field=models.CharField(max_length=50, null=True, verbose_name='Göndərən'),
        ),
    ]
