# Generated by Django 3.2.4 on 2021-09-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_sharemodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemodel',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='file.filemodel'),
        ),
    ]
